steps:
  - label: Check Nix flake
    commands:
      - nix-shell --run 'nix flake check'

  - wait

  - label: Deploy
    commands:
      - nix run -f. inputs.deploy-rs.defaultPackage.x86_64-linux
          -c deploy
    branches: "release"
